repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^backend/
      - id: end-of-file-fixer
        files: ^backend/

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: ^backend/

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - pep8-naming==0.13.0
        files: ^backend/
