name: chatsql

services:
  backend:
    build:
        context: ./backend
        dockerfile: ./Dockerfile
    command: fastapi dev app.py --host 0.0.0.0
    ports:
      - '8000:8000'
    entrypoint:
      - /usr/src/entrypoint-backend.sh
    env_file:
      - backend/.env
    volumes:
      - ./backend/app:/usr/src/app
      - backend-db-volume:/opt/chatsql

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    entrypoint:
      - /usr/src/app/entrypoint-frontend.sh
    env_file:
      - frontend/.env
    links:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/environments:/usr/src/app/environments
      - ./frontend/index.html:/usr/src/app/index.html
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  backend-db-volume:
    external: false
