services:
  backend:
    build:
        context: ./backend
        dockerfile: ./Dockerfile
    command: fastapi dev app.py --host 0.0.0.0
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    links:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/environments:/usr/src/app/environments
      - ./frontend/index.html:/usr/src/app/index.html
    extra_hosts:
      - "host.docker.internal:host-gateway"
