name: Build Artifact 
run-name: Build Artifact on PR Merge

# Trigger: pull request sul main o sul develop
on:
  push:
    branches: 
      - feature-update-workflow

# Unità di lavoro all'interno del workflow
jobs:
  build:

    # Esecuzione in ambiente Ubuntu con le ultime versioni di pacchetti e librerie
    runs-on: ubuntu-latest

    # Azioni atomiche eseguite in sequenza all'interno del job
    steps:

    # Clonazione del repository all'interno dell'ambiente di esecuzione del job
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          # Recupero tutta la cronologia (branch e tag)
          fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '20'

    - name: Check Node Version
      run: node -v

    - name: Installing dependencies
      run: |
        cd frontend
        npm i
    
    - name: Build Unit Test
      run: |
        cd frontend
        npm run test

    # Creazione della directory principale
    - name: Parent Folder
      continue-on-error: true
      run: |
        ls

    # Pubblicazione dell'artefatto generato durante il processo di build
    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChatSQL/MVP
        path: ./
