name: Formatting BE & FE 
run-name: Formatting BE & FE when PR is updated

# Definizione dei permessi
permissions:       
  contents: write
  pull-requests: write

# Trigger: pull request aperta o aggiornata
on:
  push:
    branches-ignore:
      - main
      - develop

# Unità di lavoro all'interno del workflow
jobs:
  formatting:
    # Esecuzione in ambiente Ubuntu con le ultime versioni di pacchetti e librerie
    runs-on: ubuntu-latest

    # Azioni atomiche eseguite in sequenza all'interno del job
    if: ${{ github.event.pull_request.draft == false }}
    steps:

    # Clonazione del repository all'interno dell'ambiente di esecuzione del job
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          # Recupero tutta la cronologia (branch e tag)
          fetch-depth: 0

    # Configura l'ambiente Node.js     
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '20'

    # Controlla la versione di Node.js
    - name: Check Node Version
      run: node -v

    # Installa le dipendenze del progetto
    - name: Installing Dependencies
      run: |
        cd ${{ github.workspace }}/frontend
        npm i

    # Esegue la formattazione del codice nel backend utilizzando pre-commit
    - name: Code Linting and Formatting (backend)
      continue-on-error: true
      run: |
        sh setup-pre-commit.sh && pre-commit run --all-files    

    # Esegue la formattazione del codice nel frontend
    - name: Code Formatting (frontend)
      run: |
        cd ${{ github.workspace }}/frontend
        npm run format

    # Esegue il push dei file formattati
    - name: Commit changes
      if: ${{ github.event.action != 'closed' }}
      run: |
        git config user.name 'Rikicavaz77'
        git config user.email 'riccardo.cavalli@studenti.unipd.it'
        git add frontend/src backend/app
        git commit -m "Apply code formatting" || true
        git checkout -b ${{ github.head_ref }}
        git pull origin ${{ github.head_ref }}
        git push origin ${{ github.head_ref }}
